# Generated by Django 4.2.4 on 2024-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkvisa', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
